version: '3'

services:
  ollama:
    container_name: ollama-service
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

  main_app:
    container_name: streamlit-ollama-ui
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=http://ollama:11434

networks:
  default:
    name: ollama-network

volumes:
  ollama_data: